name: Container

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:14-buster
    steps:
      - name: Log Node version
        run: node -v
      - name: Step with docker
        uses: docker://node:12-alpine3.14
        with:
          entrypoint: "/bin/echo"
          args: "Hello there"
      - name: Log Node version
        uses: docker://node:12-alpine3.14
        with:
          entrypoint: "/usr/local/bin/node"
          args: "-v"
  node-docker:
    runs-on: ubuntu-18.04
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\",\"address\": \"blabla\"}'"
      - name: Get users 
        run: curl http://localhost:3001/api/users
      - name: Log OS version
        run: |
          cat /etc/os-release
