name: Helper

on: push

jobs:
  default-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Maven version
        run: |
          mvn -v

  another-job:
    if: 1==2
    runs-on: ubuntu-latest
    steps:
      - name: Check for Node version
        run: |
          node -v

  yet-another-job:
    if: 1==1
    runs-on: ubuntu-latest
    steps:
      - name: Check for Java version
        run: |
          java -version