name: Helper

on:
  push:
    branches: [master]
    paths:
      - "folder1/**"
      - ".github/workflows/helper.yml"

jobs:
  default-job:
    if: 1==1
    runs-on: ubuntu-latest
    steps:
      - name: Check for Maven version
        run: |
          mvn -v

  another-job:
    if: 1==2
    runs-on: ubuntu-latest
    steps:
      - name: Check for Node version
        run: |
          node -v

  all-default-variables:
    runs-on: ubuntu-latest
    steps:
      - name: All the default variables
        run: |
          echo "CI: ${CI}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_RUN_ID: ${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"
          echo "GITHUB_JOB: ${GITHUB_JOB}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH: ${GITHUB_EVENT_PATH}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          echo "GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}"
          echo "GITHUB_API_URL: ${GITHUB_API_URL}"
          echo "GITHUB_GRAPHQL_URL: ${GITHUB_GRAPHQL_URL}"
          echo "RUNNER_NAME: ${RUNNER_NAME}"
          echo "RUNNER_OS: ${RUNNER_OS}"
          echo "RUNNER_TEMP: ${RUNNER_TEMP}"
          echo "RUNNER_TOOL_CACHE: ${RUNNER_TOOL_CACHE}"

  all-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
