name: Shell commands

on:
  push:
    branches-ignore:
      - master

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: no.1 echo a string
        run: echo "Hello"
      - name: no.2 multiline script
        run: |
          date
          pwd
          ls -la
        
  run-windows-command:
    runs-on: windows-latest
    needs: run-shell-command
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash